# Generated by Django 2.0.3 on 2019-12-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('storage_details', models.CharField(max_length=60)),
                ('screen_size', models.CharField(max_length=60)),
                ('camera_details', models.CharField(max_length=60)),
                ('battery_details', models.CharField(max_length=60)),
                ('processor', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
    ]
